// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// import Sidebar from '@/components/Sidebar';

// export default function DashboardLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <div className="h-screen flex flex-shrink-0 flex-row justify-start ">
//       <Sidebar />
//       <div className="flex-1 overflow-y-auto p-4">{children}</div>
//     </div>
//   );
// }



// // /app/application/layout.tsx
// import Sidebar from "@/components/Sidebar";

// export default function DashboardLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <div className="h-screen flex flex-shrink-0 flex-row justify-start">
//       <Sidebar />
//       <div className="flex-1 overflow-y-auto p-4">
//         {children}
//       </div>
//     </div>
//   );
// }


// // /app/application/layout.tsx
// import Sidebar from "@/components/Sidebar";

// export default function DashboardLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <div className="h-screen flex flex-shrink-0 flex-row justify-start">
//       {/* Sidebar on the left */}
//       <Sidebar />

//       {/* Everything else (nested routes) goes on the right */}
//       <div className="flex-1 overflow-y-auto p-4">
//         {children}
//       </div>
//     </div>
//   );
// }






// app/application/layout.tsx
import Sidebar from "@/components/Sidebar";

export default function ApplicationLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="h-screen flex flex-shrink-0 flex-row justify-start">
      {/* Sidebar on the left */}
      <Sidebar />

      {/* Main content on the right */}
      <div className="flex-1 overflow-y-auto p-4">
        {children}
      </div>
    </div>
  );
}
